
sbr_dictionary = ({'atlanta': 'atlanta hawks',
                   'boston': 'boston celtics',
                   'brooklyn': 'brooklyn nets',
                   'charlotte': 'charlotte hornets',
                   'chicago': 'chicago bulls',
                   'cleveland': 'cleveland cavaliers',
                   'dallas': 'dallas mavericks',
                   'denver': 'denver nuggets',
                   'detroit': 'detroit pistons',
                   'golden state': 'golden state warriors',
                   'houston': 'houston rockets',
                   'indiana': 'indiana pacers',
                   #la confirmed to be la clippers
                   'la': 'la clippers',
                   'la lakers': 'los angeles lakers',
                   'memphis': 'memphis grizzlies',
                   'miami': 'miami heat',
                   'milwaukee': 'milwaukee bucks',
                   'minnesota': 'minnesota timberwolves',
                   'new orleans': 'new orleans pelicans',
                   'new york': 'new york knicks',
                   'oklahoma city': 'oklahoma city thunder',
                   'orlando': 'orlando magic',
                   'philadelphia': 'philadelphia 76ers',
                   'phoenix': 'phoenix suns',
                   'portland': 'portland trail blazers',
                   'sacramento': 'sacramento kings',
                   'san antonio': 'san antonio spurs',
                   'toronto': 'toronto raptors',
                   'utah': 'utah jazz',
                   'washington': 'washington wizards'})
             
